# |    AdvancedChat     |
# | By jonagamerpro1234 |
# |     Version 1.1     |
# |_____________________|
#
Config:
  Update:
    Enabled: true #allows to send an update message available on the console [ Default| true ]
    Lang: en #[ en | es ] there are 2 languages available at the moment [English|Spanish]
    Notify: true #allows to send an update message available on the player [ Default| true ]
#
# |Use default prefix|
# if it is true it will use the prefix of the plugin itself, but if it is false it will use the prefix that you define in [Prefix: 'my server']
# |ChatForma Type|
# [Default] use default chat by minecraft 
# [Custom] use the chat defined in [Custom-Format] 
# [Group] use the chat defined in [Group.<name>] but you need to add the permission that you defined for the group
Settings:
  Use-Default-Prefix: true 
  Prefix: '&6[&bMy Server&6]&7'
  ChatFormat-Type: Default
  ClearChat:
    AutoClear: true
    Tick: 24000
#
# | Default |
# | This section serves as an emergency backup in case any of the other functions do not work properly. |
#
Default-Format: '<&f<name>&f> &f<msg>'
#
# | Custom |
# | here you can customize the chat in a general way that affects both ranks, groups, and has all players |
#
Custom-Format: '&6[&c<name>&6]&8 &7<msg>'
#
# | Groups |
# | here you can customize the chat of different groups or ranks in a more specific way |
# | with this format you can add more groups
# Groups:
#   Default:
#    Format: '&9|&e<name>&9|&8> &7<msg>'
#    Permission: 'advancedchat.group.default'
#
Groups:
  Default:
    Format: '&9|&e<name>&9|&8> &7<msg>'
    Permission: 'advancedchat.group.default'
  Admin:
    Format: '&9|&e<name>&9|&8> &e<msg>'
    Permission: 'advancedchat.group.admin'
  Owner:
    Format: '&9|&e<name>&9|&8> &c<msg>'
    Permission: 'advancedchat.group.owner'
#
# |Translation of messages from AdvancedChat|
# |Version: 1|
#
AdvancedChat:
  ClearChat:
    Server: '&7The chat has been cleaned'
    Player: '&7The chat has been cleaned by &b[&e<name>&b]'
  No-Permission: '&cYou dont have permission to do that!'
  No-Permission-Label: 'Ask the server owner or an administrator for help for more information.'
  Error-Args: '&cUnknown Arguments'
  Error-Console: '&cYou cannot use this command in the console'
  Reload: '&aReload Completed'
  Help-Cmd: '&b/AdvanceChat &8| &9/Ac &6Help &7 show more information of plugin'
  Help-Msg:
    - '&5> &b/AdvancedChat &8| &9/Ac &7these are the variants of the main plugin command'
    - '&5> &b/AdvancedChat &6help &7show this same message'
    - '&5> &b/AdvancedChat &6reload &7reload the plugin files'
    - '&5> &b/AdvancedChat &6info &7shows information about the plugin' 