# |    AdvancedChat     |
# | By jonagamerpro1234 |
# |     Version 1.4.0   |
# |_____________________|
#
# |Type| the types are the modes that exist according to the function they can be different or the same these are all the types that exist 
# [Default | Custom | Group ]  , this options only works on certain options not all [Normal |Experimental]
#
Config:
  Update:
    Enabled: true #allows to send an update message available on the console [ Default| true ]
    Lang: en #[ en | es ] there are 2 languages available at the moment [English|Spanish]
    Notify: true #allows to send an update message available on the player [ Default| true ]
#
# |Use default prefix|
# if it is true it will use the prefix of the plugin itself, but if it is false it will use the prefix that you define in [Prefix: 'my server']
# |ChatForma Type|
# [Default] use default chat by minecraft 
# [Custom] use the chat defined in [Custom-Format] 
# [Group] use the chat defined in [Group.<name>] but you need to add the permission that you defined for the group
# |ClearChat|
#   [AutoClear] you can activate the automatic cleaning of the chat according to the number of ticks [Default | true]
#   [Ticks] here you can define the time that the actions are automatically executed [Default | 24000], 24000 tick = 20 min
Settings:
  Use-Default-Prefix: true 
  Prefix: '&6[&bMy Server&6]&7'
  ChatFormat-Type: Default
  ClearChat:
    AutoClear: true
    Tick: 24000
#
# | Default |
# | This section serves as an emergency backup in case any of the other functions do not work properly. |
Default-Format: '<&f<name>&f> &f<msg>'
#
# | Custom |
# | here you can customize the chat in a general way that affects both ranks, groups, and has all players |
# | in custom we have a new function which is hover text this option only works if the type is in experimental its format is
#
# |this option only works in experimental to return to normal the chat change the type to [Normal]    
#    HoverEvent:  
#      Text: 'hello <name>'
#      Color: AQUA
#      Mode: Text there are three different modes which are [ Text | Entity | Item] the second and third are for testing, they can be removed at any time
Custom-Format:
  Text: '&6[&c<name>&6]&8 &7<msg>'
  Type: Normal
  HoverEvent:
    Text: '&ahello &d<name>'
    Mode: Text
#
# |World Chat|
# |A chat system that can separate the chat by regions or worlds as needed or you can also let the chat be global
# |
# World-Chat:
#  Enabled: true
#  World-List:
#    <world name>:
#      Type: Global
#      Range: 15
#
# [World-List] here you will find the worlds that will use the chat function [Local]  serves to limit the chat to a range of players according to the distance that is defined. This option depends on the [Range] | [Global] will allow all players to talk to each other
# [World Name] Here will be the name of the world in which the function can be activated but it is important that the world exists or that the name is not incorrect
# [Type] There are only two existing types which are [Local] | [Global]
# [Local]  serves to limit the chat to a range of players according to the distance that is defined. This option depends on the [Range]
# [Global] will allow all players to talk to each other
# [Range] here you can define the distance between each player that could receive the message from another [this option only works with the type | local]
#
World-Chat:
  Enabled: true
  World-List:
    World:
      Type: Global
      Range: 15
#
# | Groups |
# | here you can customize the chat of different groups or ranks in a more specific way |
# | with this format you can add more groups
# | in group we have a new function which is hover text this option only works if the type is in experimental its format is
# Groups:
#   Default:
#    Format: '&9|&e<name>&9|&8> &7<msg>'
#    Permission: 'advancedchat.group.default'
#    Type: Experimental [Default | Type: Normal ]
#
# |this option only works in experimental to return to normal the chat change the type to [Normal]    
#    HoverEvent:  
#      Text: 'hello <name>'
#      Color: AQUA
#
Groups:
  Default:
    Format: '&9|&e<name>&9|&8> &7<msg>'
    Permission: 'advancedchat.group.default'
    Type: Normal
    HoverEvent:
      Text: '&6hello &b<name>'
      Mode: Text
  Admin:
    Format: '&9|&e<name>&9|&8> &e<msg>'
    Permission: 'advancedchat.group.admin'
  Owner:
    Format: '&9|&e<name>&9|&8> &c<msg>'
    Permission: 'advancedchat.group.owner'
#
# |Filter Chat|
# |here you can filter the unwanted words on your server and have a little more control over the chat
#
# [Use-Custom-Msg] will use a custom message found in the [Message] section instead of using [Form Of Censorship] [Default | false]
# [Message] here you can define a personalized message that will be sent to the player
# [Form-Of-Censorship] this is the format that the word will be censored, for example [noob = ****] this will depend on the number of characters that the word has
# [Delay] It is the waiting time that the message will have before it is sent so that spam does not form in the player's chat [Defalt | 100 ]
#
# |The format is very simple, you just have to add the word you want to censor to the list
#  Words:
#    - 'noob'
#    - 'stupid'
#    - '<word>'
#
Filter-Chat:
  Enabled: true
  Use-Custom-Msg: false
  Message: 'you cannot use this word, it is blocked!'
  Form-Of-Censorship: '*'
  Delay: 5
  BadWords:
    - 'noob'
    - 'stupid'
    - 'fuck'
#
#
# |Translation of messages from AdvancedChat|
# |Version: 1.4|
#
AdvancedChat:
  ClearChat:
    Server: '&7The chat has been cleaned'
    Player: '&7The chat has been cleaned by &b[&e<name>&b]'
  No-Permission: '&cYou dont have permission to do that!'
  No-Permission-Label: 'Ask the server owner or an administrator for help for more information.'
  Error-Args: '&cUnknown Arguments'
  Error-Console: '&cYou cannot use this command in the console'
  Reload: '&aReload Completed'
  Help-Cmd: '&b/AdvanceChat &8| &9/Ac &6Help &7 show more information of plugin'
  Help-Msg:
    - '&5> &b/AdvancedChat &8| &9/Ac &7these are the variants of the main plugin command'
    - '&5> &b/AdvancedChat &6help &7show this same message'
    - '&5> &b/AdvancedChat &6reload &7reload the plugin files'
    - '&5> &b/AdvancedChat &6info &7shows information about the plugin' 
  Mute-Player: '&e[&b<name>&e] &cis now muted!'
  Un-Mute-Player: '&e[&b<name>&e] &ais now unmuted!'
  Alert-Mute: '&e[!] &cright now you are muted'
#
# This is the end of the configuration ... [-_-] more things coming soon
# 
# | Config File
# | Version 1.4.0-Pre-Alpha[3]